"""Structured PR review routing.

GitHub's webhook payloads for reviews, inline review comments, and issue
comments each carry different fields. This module normalizes them into
a single ``structured`` dict:

  {
    "prompt":     str  — ready to pass to agent.ainvoke
    "repo_full":  str  — "owner/name"
    "branch":     str  — PR head branch, empty for issue comments
    "feature_id": str  — feat/<id> → <id>, empty when branch doesn't match
    "file":       str  — target file for inline comments, empty otherwise
    "line":       int  — target line for inline comments, 0 otherwise
    "body":       str  — reviewer's comment text
    "reviewer":   str  — GitHub username
    "pr_url":     str  — link back so the agent can inspect the PR
  }

``apply_review_to_feature`` uses the structured dict to flip the matching
feature back to pending with a targeted heal_hint, so even if the agent's
direct ainvoke fails the loop will retry the feature with review context.
"""

from __future__ import annotations

from typing import Any

from .backlog import Backlog
from .logger import log


def build_structured_prompt(event: str, payload: dict[str, Any]) -> dict[str, Any] | None:
    """Normalize a GitHub webhook payload into the structured dict. Returns
    None when there's nothing actionable (empty body, bot-originated, etc)."""
    repo_full = (payload.get("repository") or {}).get("full_name", "")
    pr = payload.get("pull_request") or payload.get("issue") or {}
    pr_url = pr.get("html_url", "")
    head = ((payload.get("pull_request") or {}).get("head") or {})
    branch = head.get("ref", "") or ""
    feature_id = branch.removeprefix("feat/") if branch.startswith("feat/") else ""

    reviewer = ""
    body = ""
    file = ""
    line = 0

    if event == "pull_request_review":
        review = payload.get("review") or {}
        body = review.get("body") or ""
        reviewer = (review.get("user") or {}).get("login", "")
    elif event == "pull_request_review_comment":
        comment = payload.get("comment") or {}
        body = comment.get("body") or ""
        reviewer = (comment.get("user") or {}).get("login", "")
        file = comment.get("path", "") or ""
        line = int(comment.get("line") or comment.get("original_line") or 0)
    elif event == "issue_comment":
        comment = payload.get("comment") or {}
        body = comment.get("body") or ""
        reviewer = (comment.get("user") or {}).get("login", "")

    if not body.strip():
        return None
    # Ignore bot / agent echo — our auto-PR body mentions "Generated by
    # hearth-agents"; if the comment came from us, skip.
    if reviewer.endswith("[bot]") or "hearth-agents" in reviewer.lower():
        return None

    # Compose the agent-facing prompt. Structure matters: the agent should
    # see the target FIRST (which file, which line), then the feedback,
    # then explicit instruction. Matches research #3805's recommendation
    # for review-comment response loops.
    location_line = ""
    if file:
        location_line = f"Target: {file}" + (f":{line}" if line else "") + "\n"
    feature_line = f"Feature ID: {feature_id}\n" if feature_id else ""
    prompt = (
        f"GitHub {event} on {repo_full} by @{reviewer}\n"
        f"{feature_line}"
        f"PR: {pr_url}\n"
        f"Branch: {branch or '(none)'}\n"
        f"{location_line}\n"
        f"Reviewer feedback:\n"
        f"{body.strip()}\n\n"
        "Apply the reviewer's feedback. If you agree, make the change, "
        "commit with a message like ``fix(review): <one-line summary>``, "
        "and push to the SAME branch (not a new one). If you disagree, "
        "reply on the PR with a clear explanation — don't silently close "
        "the conversation. If the feedback is ambiguous, ask a clarifying "
        "question on the PR rather than guessing."
    )
    return {
        "prompt": prompt,
        "repo_full": repo_full,
        "branch": branch,
        "feature_id": feature_id,
        "file": file,
        "line": line,
        "body": body,
        "reviewer": reviewer,
        "pr_url": pr_url,
    }


def apply_review_to_feature(backlog: Backlog, structured: dict[str, Any]) -> None:
    """If the review targets a feature we manage, flip it back to pending
    with a heal_hint containing the review context. The loop then picks
    the feature up on its next iteration and applies the feedback through
    the normal retry path.

    This is belt-and-suspenders: the direct agent.ainvoke in the webhook
    handler also processes the review, but the agent may not successfully
    push a commit on that invocation (token budget, handoff failure). The
    pending flip ensures the loop reliably gets another swing."""
    fid = structured.get("feature_id") or ""
    if not fid:
        return
    feature = next((f for f in backlog.features if f.id == fid), None)
    if feature is None:
        return
    hint_parts = [
        "PR REVIEW FEEDBACK from @" + structured.get("reviewer", "?") + ":",
        structured.get("body", "")[:1500],
    ]
    if structured.get("file"):
        loc = structured["file"] + (f":{structured['line']}" if structured.get("line") else "")
        hint_parts.insert(1, f"Target: {loc}")
    feature.heal_hint = "\n".join(hint_parts)[:2000]
    prev = feature.status
    # Only flip terminal states. If the agent's already iterating, let it finish.
    if feature.status in ("done", "blocked"):
        backlog.set_status(
            fid,
            "pending",
            reason=f"pr_review from {structured.get('reviewer','?')}",
            actor="webhook",
        )
    log.info(
        "pr_review_applied",
        feature_id=fid,
        prev_status=prev,
        reviewer=structured.get("reviewer"),
    )
